version: '3.9'

services:
  app:
    image: nodejs-app:latest
    environment:
      - DB_CONNECT=testdb
      - PORT=3000
    ports:
      - "3000:3000"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:latest
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  postgres_data:

